# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a 2 jobs called "community-health-files" and "build"
  community-health-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pyrsia/.github
      - name: set custom edit URLs
        shell: python
        run: |
          import os
          for file in os.listdir('.'):
            if file.endswith('.md'):
              new_line = '---\ncustom_edit_url: https://github.com/pyrsia/.github/edit/main/{}\n---\n\n'.format(file)
              with open(file, 'r+') as file:
                content = file.read()
                file.seek(0)
                file.write(new_line + content)
      - uses: actions/upload-artifact@v2
        with:
          name: health-files
          path: '*.md'
  build:
    # The type of runner that the job will run on
    needs: community-health-files
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm

      - uses: actions/download-artifact@v2
        with:
          name: health-files
          path: docs/developer

      # Runs a set of commands using the runners shell
      - name: npm docusaurus build
        run: |
          npm ci
          npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            keep_files: true
            cname: pyrsia.io
